baseurl: http://sapser.github.io
timezone: Asia/Shanghai
encoding: utf-8
#markdown: kramdown
#markdown: redcarpet
markdown: rdiscount
highlighter: pygments
permalink: /:categories/:year/:month/:day/:title

author: sapser
author_mail: sapser@126.com
